version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*typescript*"
          - "*vitest*"
          - "*playwright*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      next:
        patterns:
          - "next"
          - "eslint-config-next"
